name: dependabot-changelog-writer
description: Generate a changelog entry from a dependabot PR
author: Marc Beck König <mbkj@tutamail.com>
inputs:
  changelog:
    description: "Location of the changelog relative to the project root"
    required: false
    default: "./CHANGELOG.md"
  commit_message:
    description: "The commit message for the changelog entry"
    required: false
    default: "Updated changelog with updated dependencies"
  committer_name:
    description: The name of the custom committer you want to use
    required: false
    default: github-actions[bot]
  committer_email:
    description: The email of the custom committer you want to use
    required: false
    default: github-actions[bot]@users.noreply.github.com
  version:
    description: "The version/H1 header to find in the CHANGELOG to add dependabot entries to"
    required: true
    default: "unreleased"
  section_header:
    description: The section header to add the changelog entry under
    required: false
    default: "Dependencies"
  push_changes:
    description: "Whether or not to add, commit, & push the modified changelog"
    required: false
    default: "true"

  push_token:
    description: "The GitHub token to use for git push, defaults to workflow token"
    required: true
    default: ${{ github.token }}

  action_download_token:
    description: "The GitHub token to use for downloading the action, defaults to workflow token"
    required: true
    default: ${{ github.token }}

outputs:
  error:
    description: "The description of any error that occurred"
    value: ${{ steps.run.outputs.error }}

runs:
  using: "composite"
  steps:
    - name: Set reusable variables
      shell: bash
      run: |
        echo "action_repo=dependabot-changelog-writer" >> $GITHUB_ENV
        echo "action_org=CramBL" >> $GITHUB_ENV
        echo "binary_name=dependabot-changelog-writer" >> $GITHUB_ENV

    - name: Add binary extension
      shell: bash
      if: runner.os == 'Windows'
      run: echo "binary_name=${{ env.binary_name }}.exe" >> $GITHUB_ENV

    # Extracts the version from the action_path to use for downloading the matching release
    # in the next step. If the final component is this repo, it means we are running the
    # integration test, so we set the version to empty string which makes the next step
    # download the latest release. We also download latest if the action is set to "@latest"
    - name: Get Action Version
      id: get_action_version
      shell: bash
      run: |
        action_path="${{ github.action_path }}"
        clean_action_path=${action_path%/./}
        action_path_final_component=${clean_action_path##*/}
        if [ "${action_path_final_component}" == "${{ env.action_repo }}" ] || [ "${action_path_final_component}" == "latest" ]; then
            version=""
        else
            version="${action_path_final_component}"
        fi
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Download Action
      shell: bash
      run: |
        gh release download ${{ steps.get_action_version.outputs.version }} --repo ${{ env.action_org }}/${{ env.action_repo }} --pattern '${{ runner.os }}.tgz'
        tar -xzf ${{ runner.os }}.tgz
      env:
        GH_TOKEN: ${{ inputs.action_download_token }}

    - name: Run Action
      shell: bash
      id: run
      run: ./${{ runner.os }}/${{ env.binary_name }} "${{ inputs.changelog }}" "${{ inputs.commit_message }}" "${{ inputs.committer_name }}" "${{ inputs.committer_email }}" "${{ inputs.version }}" "${{ inputs.section_header }}" "${{ inputs.push_changes }}"
      env:
        GH_TOKEN: ${{ inputs.action_download_token }}
        PUSH_TOKEN: ${{ inputs.push_token }}
