[package]
name = "dependabot-changelog-writer"
description = "Generate a changelog entry from a dependabot PR"
version = "0.1.0"
edition = "2021"

[dependencies]
octocrab = "0.42.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
