[package]
name = "dependabot-changelog-writer"
description = "Generate a changelog entry from a dependabot PR"
version = "1.2.0"
edition = "2021"
rust-version = "1.82"

[dependencies]
env_logger = { version = "0.11.8", default-features = false }
log = { version = "0.4.27", default-features = false }
serde_json = { version = "1.0.140", default-features = false, features = [
    "alloc",
] }
similar = { version = "2.7.0", default-features = false, features = ["text"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
tempfile = "3"
testresult = "0.4.1"
assert_cmd = "2.0.17"

# The binary is plenty fast, we optimize for size to reduce the amount that has to be downloaded when the action is run
[profile.release]
strip = true
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
