name: Test consuming this action

on:
  release:
    types: [released]
  workflow_run:
    workflows: ["Release"]
    types: ["completed"]

env:
  RUST_LOG: DEBUG
  RUST_BACKTRACE: 1

jobs:
  test_success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          push_changes: false
        env:
          USE_FAKE_EVENT_JSON: test_data/event_json/minimal_pr_opened.json

  test_error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: test
        continue-on-error: true
        uses: ./
        with:
          changelog: doesnt_exist.txt

      - name: Verify failure
        if: steps.test.outputs.error != ''
        run: echo "Failed as expected"

      - name: Unexpected success
        if: steps.test.outputs.error == ''
        run: echo "Succeeded unexpectedly" && exit 1
