name: Unit tests, linting, and formatting

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: |
          rustup override set stable
          rustup update stable

      - name: Run tests
        run: cargo test

      - name: Lint
        run: cargo clippy

      - name: Check formatting
        run: cargo fmt --check

  test-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      #pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

      - name: Run fake
        if: ${{ github.event_name }} == pull_request
        env:
          RUST_LOG: DEBUG
          GITHUB_TOKEN: ${{ github.token }}
        run: cargo run -- "CHANGELOG.md" "Some commit message" "github-actions[bot]" "github-actions[bot]@users.noreply.github.com" "version header 2" "section header 3"
